/***************************************************************/
/*                                                             */
/*      PROJECT NAME :  rx210                                  */
/*      FILE         :  rx210.c                                */
/*      DESCRIPTION  :  Main Program                           */
/*      CPU SERIES   :  RX200                                  */
/*      CPU TYPE     :  RX210                                  */
/*                                                             */
/*      This file is generated by e2 studio.                   */
/*                                                             */
/***************************************************************/                                
                                                                           
                                                                           
/************************************************************************/
/*    File Version: V1.00                                               */
/*    Date Generated: 08/07/2013                                        */
/************************************************************************/

#include "iodefine.h"
#include "RPBRX210.h"
#include "decoder_quadra.h"
#include "pwm_asser_RX210.h"
#include "asservissement.h"
#include "uart.h"
//#include "odometrie.h"


#ifdef CPPAPP
//Initialize global constructors
extern "C" void __main()
{
  static int initialized;
  if (! initialized)
    {
      typedef void (*pfunc) ();
      extern pfunc __ctors[];
      extern pfunc __ctors_end[];
      pfunc *p;

      initialized = 1;
      for (p = __ctors_end; p > __ctors; )
    (*--p) ();

    }
}
#endif 
//init des variables globales
int compteur=0;
int i = 0;

//fin init variables globales
void initialisation()
{
	uart9_init();		//init HW de l'uart
	init_hach_char();	//init of adress tables
	init_hach_sht();
	init_hach_int();
	init_hach_flt();
	active_reception();	//activation of uart reception
}	
int main(void)
{
	LED1_OFF;LED0_OFF;LED2_OFF;
	initialisation();

	char adresse=0x03;
	int valeur= -8,i = 0;
//	asm volatile("SETPSW I");

	while(1)
	{
	/*	if(SW1==0)
		{
		//	renvoi_le_recu();
			read_uart();
			while(SW1==0){}
			for(int i=0;i<1000;i++){}
		}
	}*/
		if(read_step()==1)
		{
			read_uart();
		}
	}
	return 0;
}
